name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set tag var
        id: vars
        run: echo ::set-output name=docker_tag::$(echo testcompare-servicemock:$(date +%s))
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ steps.vars.outputs.docker_tag }}
      - name: Run the Docker image
        run: docker run -d -p 5000:5000 ${{ steps.vars.outputs.docker_tag }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python for testing Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python Unit Tests
        run: python -m unittest discover test/